### ISSUE TITLE
CacheLib won't build on Centos 8.1 with kernel 5.6.13-0_fbk6_4203_g4cb46d044bc6

### ISSUE THREAD

**Issue by ghost** [facebook/CacheLib#24]
I have modified the NandWrites.cpp file, wdcWriteBytes function to support getting the bytes written for WDC drives and having issues building the CacheLib executable.  The NandWrites.txt attached file contains the changes made to NandWrites.cpp file needed to support WDC drives.  

The gmake is failing with the following errors:
CMakeFiles/cmTC_78ecd.dir/src.c.o: In function `main':
src.c:(.text+0x2f): undefined reference to `pthread_create'
src.c:(.text+0x3b): undefined reference to `pthread_detach'
src.c:(.text+0x47): undefined reference to `pthread_cancel'
src.c:(.text+0x58): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status

See the attached log and out files in the build-fail.zip file  for more details.  

[build-fail.zip](https://github.com/facebookincubator/CacheLib/files/6779355/build-fail.zip)
[NandWrites.txt](https://github.com/facebookincubator/CacheLib/files/6779315/NandWrites.txt)
